/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dDZgRo5Sw7V
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"

export default function Footer() {
  return (
    (<footer className="p-6 w-full my-20 z-50 bg-gray-950 text-gray-50">
      <div className="container max-w-7xl grid grid-cols-1 lg:grid-cols-5 md:grid-cols-3 gap-8 text-sm">
        <div className="grid gap-1">
          <h3 className="font-semibold">Redes Sociales</h3>
          <Link className="flex items-center gap-2" href="#">
            <FacebookIcon className="w-4 h-4" />
            Facebook
          </Link>
          <Link className="flex items-center gap-2" href="#">
            <TwitterIcon className="w-4 h-4" />
            Twitter
          </Link>
          <Link className="flex items-center gap-2" href="#">
            <InstagramIcon className="w-4 h-4" />
            Instagram
          </Link>
          <Link className="flex items-center gap-2" href="#">
            <LinkedinIcon className="w-4 h-4" />
            LinkedIn
          </Link>
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Mapa del Sitio</h3>
          <Link href="/">Inicio</Link>
          <Link href="/fasegrupos">Fase de grupos</Link>
          <Link href="/cuartos">Cuartos</Link>
          <Link href="/semis">Semis</Link>
          <Link href="/final">Final</Link>
          <Link href="/media">Videos/Fotos</Link>
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Contacto</h3>
          <Link href="/">nexteleven.ar@gmail.com</Link>
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Legal</h3>
          <Link href="/dmca">Términos de Servicio</Link>
          <Link href="/privacypolicy">Política de Privacidad</Link>
        </div>
        <div className="grid gap-1">
          <div className="flex items-center gap-4">
            <Link href="/" className="flex items-center gap-2" prefetch={false}>
              <TrophyIcon className="h-6 w-6" />
              <span className="text-lg font-bold">Copa América 2024</span>
            </Link>
          </div>
          <p>🎶Tema @ViusMusic​</p>
          <Link href="https://horacioabitu.com.ar" target="_blank">
          <p className="text-gray-500 dark:text-gray-400">
            © 2024 Desarrollado por Horacio Abitú. Todos los derechos reservados.
          </p>
          </Link>
        </div>
      </div>
    </footer>)
  );
}

function FacebookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>)
  );
}


function InstagramIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>)
  );
}


function LinkedinIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>)
  );
}


function TwitterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>)
  );
}

function TrophyIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
      <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
      <path d="M4 22h16" />
      <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
      <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
      <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
    </svg>
  )
}